name: Codestyle and build check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Check codestyle
        run: npx prettier --check .

      - name: Start Application
        run: node index.js &
      - name: Wait for Application to Start
        run: |
          for i in $(seq 1 10); do
            curl -sSf http://localhost:3000 > /dev/null && echo "Application is running!" && exit 0
            sleep 1
          done
          echo "Application failed to start" && exit 1